-- =============================================================================
--  Commonly-be 데이터베이스 초기화
-- =============================================================================
--  ⚠️  파괴적이다. 모든 테이블을 DROP하고 다시 만든다. 데이터가 전부 사라진다.
--
--  이 파일은 Hibernate가 `ddl-auto=create`로 실제 생성한 스키마를 pg_dump로 뽑아
--  정리한 것이다. 손으로 쓴 게 아니라 엔티티와 일치한다. 엔티티를 바꾸면 이 파일도
--  같이 고쳐야 한다 — 운영은 `ddl-auto=validate`라서 어긋나면 기동이 실패한다.
--
--  실행: psql -U <user> -d <db> -v ON_ERROR_STOP=1 -f scripts/init-db.sql
--  또는: scripts/init-db.sh (앱 중단 → 초기화 → 계정 생성 → 앱 재시작)
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. 기존 테이블 제거 (의존 순서 무시하려고 CASCADE)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS certificate_issued_items CASCADE;
DROP TABLE IF EXISTS certificates_issued      CASCADE;
DROP TABLE IF EXISTS certificate              CASCADE;
DROP TABLE IF EXISTS humans                   CASCADE;
DROP TABLE IF EXISTS file                     CASCADE;
DROP TABLE IF EXISTS refresh_token            CASCADE;
DROP TABLE IF EXISTS petitioner               CASCADE;
DROP TABLE IF EXISTS admin                    CASCADE;
DROP TABLE IF EXISTS users                    CASCADE;
DROP TABLE IF EXISTS document_number_seq      CASCADE;

-- ---------------------------------------------------------------------------
-- 2. 계정
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(100) NOT NULL,
    name             VARCHAR(20),
    -- 초기 비밀번호로 만든 계정은 바꾸기 전까지 다른 API가 403이다.
    password_changed BOOLEAN      NOT NULL DEFAULT TRUE
);

-- 담당자. users와 1:1이고 PK가 곧 FK다(@MapsId).
CREATE TABLE admin (
    user_id    BIGINT      NOT NULL PRIMARY KEY REFERENCES users(id),
    department VARCHAR(30) NOT NULL,
    role       VARCHAR(10) NOT NULL,
    CONSTRAINT admin_role_check CHECK (role IN ('ADMIN', 'USER'))
);

-- 민원인. admin 레코드가 없는 계정은 권한이 PETITIONER로 떨어진다.
CREATE TABLE petitioner (
    user_id      BIGINT      NOT NULL PRIMARY KEY REFERENCES users(id),
    phone_number VARCHAR(13) NOT NULL,
    birth_date   DATE        NOT NULL
);

-- 리프레시 토큰. 행이 있어야 유효하고, 지우면 즉시 무효다.
CREATE TABLE refresh_token (
    refresh_token_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       VARCHAR(50)  NOT NULL,
    token            VARCHAR(512) NOT NULL UNIQUE,
    expires_at       TIMESTAMP(6) NOT NULL
);

-- 만료 행 정리와 계정별 조회용. Hibernate가 만들지 않으므로 여기서 만든다.
CREATE INDEX idx_refresh_token_account_id ON refresh_token(account_id);

-- ---------------------------------------------------------------------------
-- 3. 인적사항
-- ---------------------------------------------------------------------------
-- 대상자 식별 키가 (성명, 생년월일)뿐이다. 동명이인이 같은 생년월일이면
-- 한 사람으로 합쳐진다 — 시스템 전체가 이 유니크 제약에 기대고 있다.
CREATE TABLE humans (
    human_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    gender     VARCHAR(255) NOT NULL,
    birth_date DATE         NOT NULL,
    address    VARCHAR(255),
    department VARCHAR(255),
    CONSTRAINT humans_gender_check CHECK (gender IN ('MALE', 'FEMALE')),
    CONSTRAINT uk_humans_name_birth_date UNIQUE (name, birth_date)
);

-- ---------------------------------------------------------------------------
-- 4. 재직 이력 — 한 행이 "경력 한 줄"이다. 발급 단위가 아니다.
-- ---------------------------------------------------------------------------
-- human_id는 JPA 연관관계가 아니라 raw 컬럼이다. 그래서 Hibernate가 FK를 만들지 않는다.
-- 여기서도 FK를 걸지 않는다 — 걸면 인적사항 삭제가 500이 되고, 그 경로는
-- 애플리케이션에서 409로 막는다(#64).
CREATE TABLE certificate (
    certificate_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id             BIGINT,
    name                 VARCHAR(255) NOT NULL,
    birth_date           DATE,
    gender               VARCHAR(255),
    job_title            VARCHAR(255),
    key_responsibilities VARCHAR(255),
    hire_date            DATE,
    expiration_date      DATE,
    retirement_date      DATE,
    division             VARCHAR(255),
    department           VARCHAR(255),
    reason               TEXT,
    employment_type      VARCHAR(255),
    note                 TEXT,
    CONSTRAINT certificate_gender_check CHECK (gender IN ('MALE', 'FEMALE'))
);

-- 조회·발급·수정이 전부 human_id로 대상을 찾는다. Hibernate가 만들지 않으므로 여기서 만든다.
CREATE INDEX idx_certificate_human_id ON certificate(human_id);

-- ---------------------------------------------------------------------------
-- 5. 발급 건 — 한 번 발급에 재직 이력 여러 줄이 들어간다
-- ---------------------------------------------------------------------------
CREATE TABLE certificates_issued (
    certificate_issued_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_id              BIGINT       NOT NULL,
    document_no           VARCHAR(32)  NOT NULL UNIQUE,
    purpose               VARCHAR(255),
    other_matters         TEXT,
    issue_reason          TEXT,
    total_months          INTEGER      NOT NULL,
    total_days            INTEGER      NOT NULL,
    issued_at             TIMESTAMP(6) NOT NULL,
    -- S3(Garage) object key. PDF 생성 실패 시 발급 자체가 실패하므로 보통 NOT NULL이다.
    file_path             VARCHAR(512)
);

-- 서식 재직사항 표에 찍히는 순서 그대로. line_no가 @OrderColumn이다.
CREATE TABLE certificate_issued_items (
    certificate_issued_id BIGINT  NOT NULL REFERENCES certificates_issued(certificate_issued_id),
    line_no               INTEGER NOT NULL,
    certificate_id        BIGINT  NOT NULL,
    PRIMARY KEY (line_no, certificate_issued_id),
    CONSTRAINT certificate_issued_items_line_no_check CHECK (line_no >= 0)
);

-- ---------------------------------------------------------------------------
-- 6. 업로드 파일 메타
-- ---------------------------------------------------------------------------
CREATE TABLE file (
    file_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255),
    saved_name    VARCHAR(100) NOT NULL UNIQUE,
    file_path     VARCHAR(255),
    file_size     BIGINT,
    confirmed     BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL
);

-- ---------------------------------------------------------------------------
-- 7. 문서번호 채번
-- ---------------------------------------------------------------------------
-- JPA 엔티티가 아니다. DocumentNumberGenerator의 네이티브 SQL만 쓴다.
-- ddl-auto가 만들지도 않고 validate가 부재를 잡아내지도 못한다 —
-- 빠뜨리면 앱은 정상 기동하고 첫 발급 요청에서 500이 난다.
CREATE TABLE document_number_seq (
    "year"  INTEGER NOT NULL PRIMARY KEY,
    last_no BIGINT  NOT NULL
);

COMMIT;

-- =============================================================================
--  검증 기록
-- =============================================================================
--  이 파일과 seed-admin.sql은 실제로 돌려서 확인했다.
--
--   1. 빈 Postgres 16에 init-db.sql 적용            → 10개 테이블 + 인덱스 2개 생성
--   2. seed-admin.sql 적용                          → abcd1234 / ADMIN / 민원과
--   3. JPA_DDL_AUTO=validate로 앱 기동              → 정상 기동 (스키마가 엔티티와 일치)
--   4. POST /api/auths/login (abcd1234 / abcd1234!) → 200
--   5. 같은 아이디에 abcd1234(!없음)로 로그인        → 401
--   6. GET /api/admins (ADMIN 전용)                 → 200
--   7. GET /api/users/me                            → authority=ADMIN, department=민원과
-- =============================================================================
